namespace PhotoRetouch;

public sealed record PreviewAdjustment(
    double Exposure,
    double Contrast,
    double Saturation,
    double WhiteBalance,
    double BlurSharpen,
    double BlemishRemove,
    double AcneRemove,
    double MoleAgeSpotRemove,
    double SkinSmooth,
    double PoreClean,
    double ToneEven,
    double SkinMaskRange,
    double SkinTextureProtect,
    bool HasManualSkinReference,
    System.Windows.Media.Color ManualSkinReferenceColor,
    double OvalFace,
    double FaceBalance,
    double CheekboneSoften,
    double JawlineDefine,
    double ChinLength,
    double ChinWidth,
    double FaceSymmetry,
    double EyeHeightBalance,
    double BrowHeightBalance,
    double NoseCenterBalance,
    double DoubleChin,
    double NeckJawEdge,
    System.Windows.Media.Color BackgroundColor,
    double BackgroundColorAmount,
    FaceWorkArea FaceWorkArea,
    double CurveAmount,
    CurveChannel CurveChannel,
    byte[] CurveLookup)
{
    public static PreviewAdjustment None { get; } = new(
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        45,
        70,
        false,
        System.Windows.Media.Colors.Transparent,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        System.Windows.Media.Color.FromRgb(0x4A, 0x51, 0x57),
        0,
        FaceWorkArea.Default,
        0,
        CurveChannel.All,
        CurveLookupTables.CreateIdentity());
}
